### PR TITLE
Add special characters to password in values-en/strings.xml

### PR DESCRIPTION
**Pull request by mathsw**
Some minor languages edits.
Add special characters to password format, including space.

### CODE REVIEW

**Comment by ssyijiu** [comment]
So thanks.
The latest code is in the develop branch, I will merge the code of the develop branch into the master, and then merge your PR.

**Comment by mathsw** [comment]
@ssyijiu It seems that &apos; and &quot; XML escape characters does not work, I will investigate this further today.

**Comment by ssyijiu** [comment]
OK, please PR to develop branch.

**Comment by mathsw** [comment]
I will close this PR and make the new PRs to develop branch.

**Pull request merged**
